### ISSUE TITLE
I love it 

### ISSUE THREAD

**Issue by username836** [darkarp/chromepass#11]
Please make it better

**Comment by darkarp** [comment]
Will do! Any specific suggestions that aren't included in the ToDo list?
Next release is planned for soon, but exam period is screwing up with scheduling

**Comment by username836** [comment]
What exam is it ?

**Comment by darkarp** [comment]
Anatomy, Histology, Biology, Biochem, Biophysics and Embryology.
It's a long period :/

**Comment by username836** [comment]
I'll let you know if I have any ideas
