### ISSUE TITLE
Make same for android

### ISSUE THREAD

**Issue by Vikram1807** [darkarp/chromepass#22]
**Is your feature request related to a problem? Please describe.** ---- NO

**Describe alternatives you've considered**
CAN YOU PLEASE MAKE ONE SAME FOR ANDROID WHICH CAN RUN ON TERMUX EITHER FOR ROOTED OR UNROOTED ANDROID.

**Comment by darkarp** [comment]
Will do. This project will likely not receive updates any time soon because it has been moved as part of a bigger one: https://github.com/darkarp/malkit
