### ISSUE TITLE
error: [WinError 3] The system cannot find the path specified: ''

### ISSUE THREAD

**Issue by Maoama1033** [darkarp/chromepass#24]
When I run 'py create_server.py' I get an error :

? sqlite3.connect                     imported from sqlite3
Building 'dist\server_ip.exe'.
Copy DLL C:\Users\react\AppData\Local\Programs\Python\Python37\DLLs\libssl-1_1.dll to dist
Copy DLL C:\Users\react\AppData\Local\Programs\Python\Python37\VCRUNTIME140.dll to dist
Copy DLL C:\Users\react\AppData\Local\Programs\Python\Python37\DLLs\libcrypto-1_1.dll to dist
error: [WinError 3] The system cannot find the path specified: ''

![Screenshot_3](https://user-images.githubusercontent.com/63385573/78856617-24e84c80-7a1f-11ea-912c-ea5c3868147c.png)

**Comment by raahimkhan** [comment]
Same issue

**Comment by bogoch** [comment]
Same issue

**Comment by darkarp** [comment]
Please look into Malkit, it's a replacement of Chromepass, including many more features but could work as simply Chromepass as well.
