### ISSUE TITLE
Debian install requirements error :(

### ISSUE THREAD

**Issue by spidyhackx** [darkarp/chromepass#26]
[![asciicast](https://asciinema.org/a/DpYEOmvgjnHTCSR2uJMOcrA4Y.svg)](https://asciinema.org/a/DpYEOmvgjnHTCSR2uJMOcrA4Y)

**Comment by darkarp** [comment]
Chromepass dependencies unfortunately requires Windows. Please look into Malkit, which is an improvement and includes many more functionalities, as well as everything Chromepass does.
