### ISSUE TITLE
cannot created server

### ISSUE THREAD

**Issue by ombogdan** [darkarp/chromepass#27]
C:\Users\omelc\PycharmProjects\chromepass>python create_server.py
You are using V3.9.9

    Choose how you want the passwords delivered

    (1) - [Buggy atm] via email (only Gmail supported, example@gmail.com.
        (Make sure you turn on 'allow less secure apps')

    (2) - via the client.exe (to your computer directly)

Choose a number [1-2]: 2
IP for revrse connection: 93.171.243.53
Do you want the server to display a fake Error message? [Y/N]: y
Enter a custom message or leave empty for default: Cannot open this file
Well done!
The server will be created shortly.
Don't close this window
running py2exe
Building 'dist\client.exe'.
Copy DLL C:\Users\omelc\AppData\Local\Programs\Python\Python37\DLLs\libssl-1_1.dll to dist
Copy DLL C:\Users\omelc\AppData\Local\Programs\Python\Python37\DLLs\libcrypto-1_1.dll to dist
[+] Client done building...
[+] Building server...

running py2exe

  21 missing Modules
  ------------------
? Cookie                              imported from requests.compat
? OpenSSL                             imported from urllib3.contrib.pyopenssl
? Queue                               imported from urllib3.util.queue
? backports                           imported from urllib3.packages.ssl_match_hostname
? brotli                              imported from urllib3.response, urllib3.util.request
? collections.Callable                imported from requests.compat
? collections.Mapping                 imported from requests.compat, urllib3._collections
? collections.MutableMapping          imported from requests.compat, urllib3._collections
? cookielib                           imported from requests.compat
? cryptography                        imported from requests, urllib3.contrib.pyopenssl
? simplejson                          imported from requests.compat
? socks                               imported from urllib3.contrib.socks
? urllib.getproxies                   imported from requests.compat
? urllib.getproxies_environment       imported from requests.compat
? urllib.proxy_bypass                 imported from requests.compat
? urllib.proxy_bypass_environment     imported from requests.compat
? urllib.quote                        imported from requests.compat
? urllib.quote_plus                   imported from requests.compat
? urllib.unquote                      imported from requests.compat
? urllib.unquote_plus                 imported from requests.compat
? urllib.urlencode                    imported from requests.compat

  1 submodules that appear to be missing, but could also be global names in the parent package
  ---------------------------------------------------------------------------------------------
? sqlite3.connect                     imported from sqlite3
Building 'dist\server_ip.exe'.
Copy DLL C:\Users\omelc\AppData\Local\Programs\Python\Python37\DLLs\libssl-1_1.dll to dist
Copy DLL C:\Users\omelc\AppData\Local\Programs\Python\Python37\VCRUNTIME140.dll to dist
Copy DLL C:\Users\omelc\AppData\Local\Programs\Python\Python37\DLLs\libcrypto-1_1.dll to dist
error: [WinError 3] The system cannot find the path specified: ''

**Comment by darkarp** [comment]
I will look into it. In the meantime, this project has been discontinued in favor of Malkit. It has chromepass feature included!

**Comment by darkarp** [comment]
Try again, it was just updated and completely restructured. Please go through the readme again.
I will close this issue now but if you have problems with the new release, please open a new issue.
