### ISSUE TITLE
Problem with client.exe

### ISSUE THREAD

**Issue by SafwanLjd** [darkarp/chromepass#28]
Whenever I try running client.exe I get the error shown in the picture below:

![Error](https://user-images.githubusercontent.com/59485214/108577348-5dd49b80-7329-11eb-8523-5d73a9f0a905.png)

*I'm running it on 64-Bit Windows 10*

**Comment by darkarp** [comment]
Try again, it was just updated and completely restructured. Please go through the readme again :D.
I will close this issue now but if you have problems with the new release, please open a new issue.
