### ISSUE TITLE
Port Customization And Chromium Support

### ISSUE THREAD

**Issue by SafwanLjd** [darkarp/chromepass#29]
Thank you for the awesome new 4.0.0 release!

I managed to get it to work with chromium by simply changing the value of the `chrome_dir` variable in the steal.py script to Chromium's User Data Directory, I think it'd be a good idea if you had chromium support out of the box (possibly even edge and opera since they're chromium based and probably use the same algorithm for storing passwords)

I also think that you should make it so that any port can be used (not just 80)

**Comment by darkarp** [comment]
Thanks for the feedback, it's really appreciated! 

This was quite a rushed release because I was working on many features that ended up not being here since a lot of people just wanted me to update this one first.

I'll definitely add that support soon!

**Comment by darkarp** [comment]
Added support for Chromium and Edge, and a few other improvements, released as V0.0.2

**Comment by darkarp** [comment]
To be honest, I forgot to add the port customization. Added it now and released as V4.0.2
