### ISSUE TITLE
Code enhancement

### ISSUE THREAD

**Issue by arrzdev** [darkarp/chromepass#31]
Sugestão "steal.py"
Linhas "138-142"

#STEAL.PY
#LINES 138-142

Código demonstrativo:

```
#dummy var
name = "t-name"
decrypted = "t-decrypted"
url = "t-url"

#init dict
cookies = {"t-url":[]}

##############################################

#before
cookie_obj = {}
cookie_obj["name"] = name
cookie_obj["value"] = decrypted
cookie_obj["domain"] = url

cookies[url].append(cookie_obj)

#before output
print(f"BEFORE: {cookies}")

##############################################

#reset dict
cookies[url] = []

#after
cookies[url].append(
    {
        "name": name,
        "value": decrypted,
        "domain": url
    }
)

#after output
print(f"AFTER: {cookies}")
```

Não é nada muito significativo e de todo muda a forma como o código se comporta, mas assim fica escrito de forma mais "pythonizada" e obtemos um codigo com uma leitura simplificada

@arrz#8714

**Comment by darkarp** [comment]
Mudei para ser um pouco mais "pythonic". Contudo, nao gosto de colocar objectos construidos dentro de um append, prefiro separa o objecto e o append, fica menos messy.
