### ISSUE TITLE
Batch / Shell Scripts for building

### ISSUE THREAD

**Issue by iCrazyBlaze** [darkarp/chromepass#33]
**Is your feature request related to a problem? Please describe.**
The README has a lot of steps that can take a while to complete, for example, the build process from the Demo, and the "AV Detection" segment of the readme instruction.

**Describe the solution you'd like**
.bat or .sh files can be used to automate most (if not all) of the steps necessary to build the application. Alternatively, a Python script can be used to run everything, which could make supporting cross-platform usage easier.

**Comment by darkarp** [comment]
A new update is coming where the build system will be replaced by a better one. The whole setup will be done automatically.

**Comment by cybernoob13123** [comment]
@darkarp 
Sir how to contact you directly
I contact your email many time
But no response
Thanks you sir

**Comment by darkarp** [comment]
@cybernoob13123 Please send me another email at `mario@whitehathacking.tech` or join our [discord server](https://discord.gg/8xHn6Fr).

**Comment by cybernoob13123** [comment]
@darkarp 
Sir I join your discord early,but I cannot write any thing on your dc server, which is your one dc account. I want to contact

**Comment by johnsmith1232541** [comment]
@cybernoob13123 MarioHS#7100 is my account. Please do not request illegal activities as I will not accept them. To talk on discord you must accept the rules btw, meaning you should click on the reaction at the bottom of rules.

**Comment by darkarp** [comment]
Redesigned building system. Please go through the readme again. However, it is simpler. When you try to use `create.py` it will check for dependencies and ask if you want to install them. You must be in an Admin powershell to install the dependencies and make sure you close and reopen to use the program normally. 

The client is now faster, a bit more lightweight and more undetectable. However, it takes longer to compile.
