### ISSUE TITLE
error: linker `link.exe` not found

### ISSUE THREAD

**Issue by VshivayaGnida** [darkarp/chromepass#37]
**Describe the bug**
After running create.py is not located link.exe. for more information, see the screenshot. And the code from powershell.

**Screenshots**
![image](https://user-images.githubusercontent.com/81504947/121188337-36cbb680-c893-11eb-8af4-ee7974d4227d.png)

**Software**
 - OS:  Windows 10 Pro x64
 - Python Version 3.9.5

**Additional context**
PS C:\Users\VshivayaGnida\chromepass> python create.py --error
[i] Checking dependencies...
[+] Building Server
[+] Server build successful.
[+] Building Client
cd templates\chromepass-build; cargo build --release;
   Compiling winapi v0.3.9

   Compiling typenum v1.13.0

   Compiling libc v0.2.90

   Compiling log v0.4.14

   Compiling serde v1.0.124

   Compiling memchr v2.3.4

   Compiling ntapi v0.3.6

   Compiling proc-macro2 v1.0.24

   Compiling syn v1.0.64

   Compiling futures-sink v0.3.13

   Compiling httparse v1.3.5

   Compiling cc v1.0.67

   Compiling opaque-debug v0.3.0

error: linker `link.exe` not found

  |

  = note: ÐÐµ ÑÐ´Ð°ÐµÑÑÑ Ð½Ð°Ð¹ÑÐ¸ ÑÐºÐ°Ð·Ð°Ð½Ð½ÑÐ¹ ÑÐ°Ð¹Ð». (os error 2)

note: the msvc targets depend on the msvc linker but `link.exe` was not found

note: please ensure that VS 2013, VS 2015, VS 2017 or VS 2019 was installed with the Visual C++ option

error: aborting due to previous error

error: linker `link.exe` not found

  |

  = note: ÐÐµ ÑÐ´Ð°ÐµÑÑÑ Ð½Ð°Ð¹ÑÐ¸ ÑÐºÐ°Ð·Ð°Ð½Ð½ÑÐ¹ ÑÐ°Ð¹Ð». (os error 2)

note: the msvc targets depend on the msvc linker but `link.exe` was not found

note: please ensure that VS 2013, VS 2015, VS 2017 or VS 2019 was installed with the Visual C++ option

error: aborting due to previous error

error: could not compile `log`

To learn more, run the command again with --verbose.

warning: build failed, waiting for other jobs to finish...

error: linker `link.exe` not found

  |

  = note: ÐÐµ ÑÐ´Ð°ÐµÑÑÑ Ð½Ð°Ð¹ÑÐ¸ ÑÐºÐ°Ð·Ð°Ð½Ð½ÑÐ¹ ÑÐ°Ð¹Ð». (os error 2)

note: the msvc targets depend on the msvc linker but `link.exe` was not found

note: please ensure that VS 2013, VS 2015, VS 2017 or VS 2019 was installed with the Visual C++ option

error: aborting due to previous error

error: linker `link.exe` not found

  |

  = note: ÐÐµ ÑÐ´Ð°ÐµÑÑÑ Ð½Ð°Ð¹ÑÐ¸ ÑÐºÐ°Ð·Ð°Ð½Ð½ÑÐ¹ ÑÐ°Ð¹Ð». (os error 2)

note: the msvc targets depend on the msvc linker but `link.exe` was not found

note: please ensure that VS 2013, VS 2015, VS 2017 or VS 2019 was installed with the Visual C++ option

error: aborting due to previous error

error: linker `link.exe` not found

  |

  = note: ÐÐµ ÑÐ´Ð°ÐµÑÑÑ Ð½Ð°Ð¹ÑÐ¸ ÑÐºÐ°Ð·Ð°Ð½Ð½ÑÐ¹ ÑÐ°Ð¹Ð». (os error 2)

note: the msvc targets depend on the msvc linker but `link.exe` was not found

note: please ensure that VS 2013, VS 2015, VS 2017 or VS 2019 was installed with the Visual C++ option

error: aborting due to previous error

error: linker `link.exe` not found

  |

  = note: ÐÐµ ÑÐ´Ð°ÐµÑÑÑ Ð½Ð°Ð¹ÑÐ¸ ÑÐºÐ°Ð·Ð°Ð½Ð½ÑÐ¹ ÑÐ°Ð¹Ð». (os error 2)

note: the msvc targets depend on the msvc linker but `link.exe` was not found

note: please ensure that VS 2013, VS 2015, VS 2017 or VS 2019 was installed with the Visual C++ option

error: aborting due to previous error

error: linker `link.exe` not found

  |

  = note: ÐÐµ ÑÐ´Ð°ÐµÑÑÑ Ð½Ð°Ð¹ÑÐ¸ ÑÐºÐ°Ð·Ð°Ð½Ð½ÑÐ¹ ÑÐ°Ð¹Ð». (os error 2)

note: the msvc targets depend on the msvc linker but `link.exe` was not found

note: please ensure that VS 2013, VS 2015, VS 2017 or VS 2019 was installed with the Visual C++ option

error: aborting due to previous error

error: linker `link.exe` not found

  |

  = note: ÐÐµ ÑÐ´Ð°ÐµÑÑÑ Ð½Ð°Ð¹ÑÐ¸ ÑÐºÐ°Ð·Ð°Ð½Ð½ÑÐ¹ ÑÐ°Ð¹Ð». (os error 2)

note: the msvc targets depend on the msvc linker but `link.exe` was not found

note: please ensure that VS 2013, VS 2015, VS 2017 or VS 2019 was installed with the Visual C++ option

error: aborting due to previous error

error: linker `link.exe` not found

  |

  = note: ÐÐµ ÑÐ´Ð°ÐµÑÑÑ Ð½Ð°Ð¹ÑÐ¸ ÑÐºÐ°Ð·Ð°Ð½Ð½ÑÐ¹ ÑÐ°Ð¹Ð». (os error 2)

note: the msvc targets depend on the msvc linker but `link.exe` was not found

note: please ensure that VS 2013, VS 2015, VS 2017 or VS 2019 was installed with the Visual C++ option

error: aborting due to previous error

error: linker `link.exe` not found

  |

  = note: ÐÐµ ÑÐ´Ð°ÐµÑÑÑ Ð½Ð°Ð¹ÑÐ¸ ÑÐºÐ°Ð·Ð°Ð½Ð½ÑÐ¹ ÑÐ°Ð¹Ð». (os error 2)

note: the msvc targets depend on the msvc linker but `link.exe` was not found

note: please ensure that VS 2013, VS 2015, VS 2017 or VS 2019 was installed with the Visual C++ option

error: aborting due to previous error

error: build failed

Traceback (most recent call last):
  File "C:\Users\VshivayaGnida\chromepass\create.py", line 203, in <module>
    parse_arguments()
  File "C:\Users\VshivayaGnida\chromepass\create.py", line 197, in parse_arguments
    client = build_client(ip_address=args.ip, error_bool=args.error_bool, error_message=args.message,
  File "C:\Users\VshivayaGnida\chromepass\create.py", line 101, in build_client
    shutil.copyfile(
  File "C:\Users\VshivayaGnida\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'templates/chromepass-build/target/release/chromepass.exe'

**Comment by RandomVersion** [comment]
same issue :/

**Comment by darkarp** [comment]
This is a dependency issue. A fix is in the works. Unfortunately I'm extremely busy at the moment but I'm planning on fixing all of these issues as soon as I can!
