### ISSUE TITLE
"There isn't enough memory to complete this action"

### ISSUE THREAD

**Issue by Genus-learner** [darkarp/chromepass#38]
Installed the latest version of chromepass.
Everything went smoothly, no errors.
But when I try to run the client file.
This error occurs:
![image](https://user-images.githubusercontent.com/83723816/129330236-76eb9b99-69d6-40d9-bd79-cd739079c0bf.png)

I tried closing everything else but the error stays.

**Comment by darkarp** [comment]
Yes, this is actually not a bug. Maybe it should be better explained in the README. The client has the ability to create a fake error message (the one you're seeing), as an example way to make it look like the program couldn't run, so it looks less suspicious. If the program runs and does nothing, it may be suspicious. If that message appears, the program ran successfully, it's just a fake message.

The error message can be customized by the `--message` flag, like this: `python create.py --ip 127.0.0.1 --error --message A custom error has happened`

Did you create the client using the `--error` flag? It's actually supposed to be disabled by default.

**Comment by darkarp** [comment]
Is this problem clarified or is there still an issue?

**Comment by Genus-learner** [comment]
Oh sorry lol
That didnt happen in the last version so I wasnt aware of it.
Ok I'll play around with it some more 
thanks
