### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by rikuru-to865** [darkarp/chromepass#43]
--- stderr

error occurred: Failed to find tool. Is `cl.exe` installed? (see https://github.com/alexcrichton/cc-rs#compile-time-requirements for help)

warning: build failed, waiting for other jobs to finish...
error: build failed
[-] Client couldn't be copied: [Errno 2] No such file or directory: 'templates/chromepass-build/target/release/chromepass.exe'
[-] Error building the clien

i runned
python create.py --ip 127.0.0.1

**Comment by darkarp** [comment]
Try the following:

  1. [Install visual studio community edition](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=Community&rel=17)

  2. [Install rustup](https://win.rustup.rs/x86_64) (or uninstall and reinstall)

  3. Restart

  This should take care of all the dependencies, in case the automatic installer failed. 

It's recommended you do this on a virtual machine just to avoid having to install a bunch of things on your host and to allow easy access to snapshots.

**Comment by rikuru-to865** [comment]
thank you
i'll try it

**Comment by rikuru-to865** [comment]
I tried it in a virtual environment and it worked fine. Thank you.
