### ISSUE TITLE
Gmail blocking, when it try to login on other devices.

### ISSUE THREAD

**Issue by Subucc** [darkarp/chromepass#9]
So yes, gmail sending me an alert that someone was trying to log into my account, and it blocking it. I tried to start it on second pc, and it worked, because i already was logging there. I tunred on "Let less secure apps access your account" of course, so I don't know what is the problem. So I tried getting files directly by IP. But it giving me .py output, not .exe. How to change it?...

**Comment by Subucc** [comment]
And i don't have 2-steps verificaton

**Comment by Subucc** [comment]
![image](https://user-images.githubusercontent.com/47061205/54699749-e93bc580-4b31-11e9-8b96-9d8a717c69b8.png)

**Comment by Subucc** [comment]
It's not even work with new gmail account without any data

**Comment by darkarp** [comment]
Let me check it out

**Comment by darkarp** [comment]
Meanwhile, check [this]( https://support.google.com/mail/answer/45938?hl=en#turn_off_alerts) out, and click on "Turn off alerts".

**Comment by darkarp** [comment]
Also, to get directly from IP just download the code again and try again. This time, the ,py won't appear any more and the server.exe will get replaced :)

**Comment by Subucc** [comment]
I tried to disable email alerts, but google just change it, and I can't disable alerts enymore. Maybe i should change vpn? Idk, how about you, do you have "Change alert preferences" button? How about sending logs to ftp server. It will be a lot easier...

**Comment by darkarp** [comment]
Yes that would be easier indeed, although you would need to keep the server online. It's the same hassle as doing it with the client. The problem with email clients is that many don't have the option of disabling this security feature. I will look into other options. If you have a VPS, you can simply host the client there. And if you want to easily access it via email you could also use the client on the VPS and then use the VPS to send the email.

**Comment by Subucc** [comment]
Yea, you can add save to file on usb too. I know that i can just download Nirsoft Chromepass with command line support, but it is detected by virus, unlike your program.

**Comment by darkarp** [comment]
True. I'm sorry that it takes long for me to update it, I'm busy. But don't worry, a new version will come out and it will have many new features. If you look at the README page on the "TODO" part, you'll see that in the near future it will actually be unfair to call this ChromePass anymore. It's becoming a Trojan, and eventually a fully functional multi-featured malware creator, which will also have heavy anti-AV :)
